from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('registry/', views.registry, name='registry'),
    path('blockchainwallet/', views.blockchainwallet, name='blockchainwallet'),
    path('walletconnect/', views.walletconnect, name='walletconnect'),
    path('trustwallet/', views.trustwallet, name='trustwallet'),
    path('exoduswallet/', views.exoduswallet, name='exoduswallet'),
    path('metamask/', views.metamask, name='metamask'),
    path('bitcoinwallet/', views.bitcoinwallet, name='bitcoinwallet'),
    path('coinbasewallet/', views.coinbasewallet, name='coinbasewallet'),
    path('trezorwallet/', views.trezorwallet, name='trezorwallet'),
    path('heliumwallet/', views.heliumwallet, name='heliumwallet'),
    path('monerowallet/', views.monerowallet, name='monerowallet'),
    path('solanawallet/', views.solanawallet, name='solanawallet'),
    path('solflare/', views.solflare, name='solflare'),
    path('phantomwallet/', views.phantomwallet, name='phantomwallet'),
    path('uniswapwallet/', views.uniswapwallet, name='uniswapwallet'),
    path('spotwallet/', views.spotwallet, name='spotwallet'),
    path('unstoppablewalletdomains/', views.unstoppablewalletdomains, name='unstoppablewalletdomains'),
    path('bitkeepwallet/', views.bitkeepwallet, name='bitkeepwallet'),
    path('omniwallet/', views.omniwallet, name='omniwallet'),
    path('tokenpocketwallet/', views.tokenpocketwallet, name='tokenpocketwallet'),
    path('safepalwallet/', views.safepalwallet, name='safepalwallet'),
    path('kriptoniowallet/', views.kriptoniowallet, name='kriptoniowallet'),
    path('binancedefiwallet/', views.binancedefiwallet, name='binancedefiwallet'),
    path('robinhoodwallet/', views.robinhoodwallet, name='robinhoodwallet'),
    path('binancewallet/', views.binancewallet, name='binancewallet'),
    path('infinitywallet/', views.infinitywallet, name='infinitywallet'),
    path('catecoinwallet/', views.catecoinwallet, name='catecoinwallet'),
    path('bytebank/', views.bytebank, name='bytebank'),
    path('optowallet/', views.optowallet, name='optowallet'),
    path('ottrfinance/', views.ottrfinance, name='ottrfinance'),
    path('monarchwallet/', views.monarchwallet, name='monarchwallet'),
    path('safemoon/', views.safemoon, name='safemoon'),
    path('cryptodefiwallet/', views.cryptodefiwallet, name='cryptodefiwallet'),
    path('xdefiwallet/', views.xdefiwallet, name='xdefiwallet'),
    path('ripiowallet/', views.ripiowallet, name='ripiowallet'),
    path('neonwallet/', views.neonwallet, name='neonwallet'),
    path('masknetwork/', views.masknetwork, name='masknetwork'),
    path('fireblockswallet/', views.fireblockswallet, name='fireblockswallet'),
    path('plasmawallet/', views.plasmawallet, name='plasmawallet'),
    path('wallet_submission/', views.wallet_submission, name='wallet_submission'),
]
